// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {ide} from '../models';
import {orchestrator} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<orchestrator.Task>;

export function GetPoolSummaries():Promise<Array<orchestrator.PoolSummary>>;

export function GetWorkspace(arg1:string):Promise<ide.Workspace>;

export function ListAttempts(arg1:string):Promise<Array<orchestrator.Attempt>>;

export function ListRecentWorkspaces():Promise<Array<ide.WorkspaceSummary>>;

export function ListTasks():Promise<Array<orchestrator.Task>>;

export function OpenWorkspaceByID(arg1:string):Promise<string>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function RunTask(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function GetAvailablePools():Promise<Array<{id: string, name: string, description?: string}>>;

export function CreateChatSession():Promise<any>;

export function SendChatMessage(arg1:string,arg2:string):Promise<any>;

export function GetChatHistory(arg1:string):Promise<Array<any>>;

// Execution API
export function StartExecution():Promise<void>;

export function PauseExecution():Promise<void>;

export function ResumeExecution():Promise<void>;

export function StopExecution():Promise<void>;

// Backlog API
export function GetBacklogItems():Promise<Array<orchestrator.BacklogItem>>;

export function ResolveBacklogItem(arg1:string,arg2:string):Promise<void>;

export function DeleteBacklogItem(arg1:string):Promise<void>;
