// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {orchestrator} from '../models';
import {ide} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<orchestrator.Task>;

export function GetWorkspace(arg1:string):Promise<ide.Workspace>;

export function ListTasks():Promise<Array<orchestrator.Task>>;

export function LoadWorkspace(arg1:string):Promise<string>;

export function RunTask(arg1:string):Promise<void>;

export function ScheduleTask(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;
